#version 430 core
layout(local_size_x = 256) in;

struct BladeIndex {
    float distance;
    uint index;
};


layout(std430, binding = 1) readonly buffer Positions {
    vec4 positions[];
};

layout(std430, binding = 0) writeonly buffer SortedIndices {
    BladeIndex bladeIndicies[];
};

uniform vec3 cameraPos;

void main(){
    uint idx = gl_GlobalInvocationID.x;
    vec3 p = positions[idx].xyz;
    bladeIndicies[idx].distance = distance(p, cameraPos);
    bladeIndicies[idx].index = idx;
}